services:
  app:
    build: .
    ports:
      - '${PORT:-8000}:${PORT:-8000}'
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:7
    profiles:
      - local-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
